### ISSUE TITLE
Error: Call to undefined method atk4\ui\Form::addTo()

### ISSUE THREAD

**Issue by humanitiesclinic** [atk4/ui#1321]
With this code:

```
<?php
use \atk4\ui\Form; // just declared once at the top of your file
require 'vendor/autoload.php';


// Initialize App and Layout first
$app = new \atk4\ui\App('My First App');
$app->initLayout('Centered');

// Your application starts here
$app->layout->add('HelloWorld');

$form = Form::addTo($app);
$form->addField('email');

?>
```

I am getting:

Error: Call to undefined method atk4\ui\Form::addTo() (in /Users/user/Documents/canla_prods/agileui_test.php:13)
#0 {main}

May I know what I am doing wrong?

**Comment by DarkSide666** [comment]
1. require should go first
2. in use statement remove leading slash
3. $app->initLayout('Centered'); should be $app->initLayout(\atk4\ui\Layout\Centered::class);
4. show us your composer.json file and use latest versions from develop branch if possible.

**Comment by humanitiesclinic** [comment]
I am having 1.7
that's the version composer installs by default
by I saw that now 2.1 is the latest on GitHub. which should be the correct version to use?

**Comment by humanitiesclinic** [comment]
this is my composer.json:

```
{
    "require": {
        "prestashop/prestashop-webservice-lib": "dev-master",
        "vlucas/spot2": "~2.0",
        "atk4/ui": "^1.7"
    }
}

```
composer.lock:

```
{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
        "This file is @generated automatically"
    ],
    "content-hash": "7a2622fa4c542a7bbaad28cb638aaafa",
    "packages": [
        {
            "name": "atk4/core",
            "version": "1.3.10",
            "source": {
                "type": "git",
                "url": "https://github.com/atk4/core.git",
                "reference": "f74ab9f8f8d3cbdac0aad40282703c69179e1d69"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/atk4/core/zipball/f74ab9f8f8d3cbdac0aad40282703c69179e1d69",
                "reference": "f74ab9f8f8d3cbdac0aad40282703c69179e1d69",
                "shasum": ""
            },
            "require": {
                "php": ">=5.6.0",
                "psr/log": "~1.0"
            },
            "require-dev": {
                "codeclimate/php-test-reporter": "*",
                "phpunit/phpunit": "<6",
                "satooshi/php-coveralls": "^1.0"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "atk4\\core\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Romans Malinovskis",
                    "email": "romans@agiletoolkit.org",
                    "homepage": "https://nearly.guru/"
                }
            ],
            "description": "Agile Core - collection of PHP Traits for designing object-oriented frameworks",
            "homepage": "https://github.com/atk4/core",
            "keywords": [
                "Agile Toolkit",
                "framework",
                "php",
                "trains"
            ],
            "time": "2019-02-04T13:37:55+00:00"
        },
        {
            "name": "atk4/data",
            "version": "1.4.1",
            "source": {
                "type": "git",
                "url": "https://github.com/atk4/data.git",
                "reference": "073dfb1d6c205f4f1a85759b46ba024a02887b1e"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/atk4/data/zipball/073dfb1d6c205f4f1a85759b46ba024a02887b1e",
                "reference": "073dfb1d6c205f4f1a85759b46ba024a02887b1e",
                "shasum": ""
            },
            "require": {
                "atk4/core": "^1.3",
                "atk4/dsql": "^1.2",
                "php": ">=7.0.0"
            },
            "require-dev": {
                "atk4/schema": "*",
                "codeclimate/php-test-reporter": "*",
                "phpunit/dbunit": ">=1.2",
                "phpunit/phpcov": "*",
                "phpunit/phpunit": "<6"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "atk4\\data\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Romans Malinovskis",
                    "email": "romans@agiletoolkit.org",
                    "homepage": "https://nearly.guru/"
                }
            ],
            "description": "Agile Data - Database access abstraction framework",
            "homepage": "https://github.com/atk4/data",
            "keywords": [
                "Active Record",
                "builder",
                "framework",
                "mongodb",
                "mysql",
                "nosql",
                "orm",
                "postgresql",
                "query",
                "sql"
            ],
            "time": "2019-02-23T22:00:56+00:00"
        },
        {
            "name": "atk4/dsql",
            "version": "1.2.6",
            "source": {
                "type": "git",
                "url": "https://github.com/atk4/dsql.git",
                "reference": "82b39c73ef693a29d4e62fc826b4686125b298b9"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/atk4/dsql/zipball/82b39c73ef693a29d4e62fc826b4686125b298b9",
                "reference": "82b39c73ef693a29d4e62fc826b4686125b298b9",
                "shasum": ""
            },
            "require": {
                "atk4/core": "^1.3",
                "php": ">=5.6.0"
            },
            "require-dev": {
                "codeclimate/php-test-reporter": "*",
                "phpunit/dbunit": ">=1.2",
                "phpunit/phpcov": "*",
                "phpunit/phpunit": "<6"
            },
            "suggest": {
                "jdorn/sql-formatter": "*"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "atk4\\dsql\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Romans Malinovskis",
                    "email": "romans@agiletoolkit.org",
                    "homepage": "https://nearly.guru/"
                }
            ],
            "description": "Dynamic SQL Builder in PHP",
            "homepage": "http://agiletoolkit.org/",
            "keywords": [
                "builder",
                "framework",
                "orm",
                "sql"
            ],
            "time": "2019-02-04T13:45:00+00:00"
        },
        {
            "name": "atk4/ui",
            "version": "1.7.1",
            "source": {
                "type": "git",
                "url": "https://github.com/atk4/ui.git",
                "reference": "1ca8f16ab7e4a499e9e25690eb237ab4be82940c"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/atk4/ui/zipball/1ca8f16ab7e4a499e9e25690eb237ab4be82940c",
                "reference": "1ca8f16ab7e4a499e9e25690eb237ab4be82940c",
                "shasum": ""
            },
            "require": {
                "atk4/core": "<2",
                "atk4/data": "<2",
                "php": ">=5.6.0"
            },
            "require-dev": {
                "behat/behat": "^3.4",
                "behat/mink-extension": "^2.2",
                "behat/mink-selenium2-driver": "^1.3",
                "codeclimate/php-test-reporter": "*",
                "fzaninotto/faker": "*",
                "phpunit/phpcov": "^3.0",
                "phpunit/phpunit": "<6"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "atk4\\ui\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Romans Malinovskis",
                    "email": "romans@agiletoolkit.org",
                    "homepage": "https://nearly.guru/"
                }
            ],
            "description": "Agile UI - Web Component Framework written in PHP",
            "homepage": "https://agiletoolkit.org/ui",
            "keywords": [
                "button",
                "component",
                "crud",
                "form",
                "framework",
                "gadget",
                "grid",
                "render",
                "ui",
                "web",
                "widget"
            ],
            "time": "2019-06-12T01:56:02+00:00"
        },
        {
            "name": "doctrine/cache",
            "version": "1.10.1",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/cache.git",
                "reference": "35a4a70cd94e09e2259dfae7488afc6b474ecbd3"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/doctrine/cache/zipball/35a4a70cd94e09e2259dfae7488afc6b474ecbd3",
                "reference": "35a4a70cd94e09e2259dfae7488afc6b474ecbd3",
                "shasum": ""
            },
            "require": {
                "php": "~7.1 || ^8.0"
            },
            "conflict": {
                "doctrine/common": ">2.2,<2.4"
            },
            "require-dev": {
                "alcaeus/mongo-php-adapter": "^1.1",
                "doctrine/coding-standard": "^6.0",
                "mongodb/mongodb": "^1.1",
                "phpunit/phpunit": "^7.0",
                "predis/predis": "~1.0"
            },
            "suggest": {
                "alcaeus/mongo-php-adapter": "Required to use legacy MongoDB driver"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.9.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Doctrine\\Common\\Cache\\": "lib/Doctrine/Common/Cache"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Guilherme Blanco",
                    "email": "guilhermeblanco@gmail.com"
                },
                {
                    "name": "Roman Borschel",
                    "email": "roman@code-factory.org"
                },
                {
                    "name": "Benjamin Eberlei",
                    "email": "kontakt@beberlei.de"
                },
                {
                    "name": "Jonathan Wage",
                    "email": "jonwage@gmail.com"
                },
                {
                    "name": "Johannes Schmitt",
                    "email": "schmittjoh@gmail.com"
                }
            ],
            "description": "PHP Doctrine Cache library is a popular cache implementation that supports many different drivers such as redis, memcache, apc, mongodb and others.",
            "homepage": "https://www.doctrine-project.org/projects/cache.html",
            "keywords": [
                "abstraction",
                "apcu",
                "cache",
                "caching",
                "couchdb",
                "memcached",
                "php",
                "redis",
                "xcache"
            ],
            "time": "2020-05-27T16:24:54+00:00"
        },
        {
            "name": "doctrine/dbal",
            "version": "v2.9.3",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/dbal.git",
                "reference": "7345cd59edfa2036eb0fa4264b77ae2576842035"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/doctrine/dbal/zipball/7345cd59edfa2036eb0fa4264b77ae2576842035",
                "reference": "7345cd59edfa2036eb0fa4264b77ae2576842035",
                "shasum": ""
            },
            "require": {
                "doctrine/cache": "^1.0",
                "doctrine/event-manager": "^1.0",
                "ext-pdo": "*",
                "php": "^7.1"
            },
            "require-dev": {
                "doctrine/coding-standard": "^5.0",
                "jetbrains/phpstorm-stubs": "^2018.1.2",
                "phpstan/phpstan": "^0.10.1",
                "phpunit/phpunit": "^7.4",
                "symfony/console": "^2.0.5|^3.0|^4.0",
                "symfony/phpunit-bridge": "^3.4.5|^4.0.5"
            },
            "suggest": {
                "symfony/console": "For helpful console commands such as SQL execution and import of files."
            },
            "bin": [
                "bin/doctrine-dbal"
            ],
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "2.9.x-dev",
                    "dev-develop": "3.0.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Doctrine\\DBAL\\": "lib/Doctrine/DBAL"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Guilherme Blanco",
                    "email": "guilhermeblanco@gmail.com"
                },
                {
                    "name": "Roman Borschel",
                    "email": "roman@code-factory.org"
                },
                {
                    "name": "Benjamin Eberlei",
                    "email": "kontakt@beberlei.de"
                },
                {
                    "name": "Jonathan Wage",
                    "email": "jonwage@gmail.com"
                }
            ],
            "description": "Powerful PHP database abstraction layer (DBAL) with many features for database schema introspection and management.",
            "homepage": "https://www.doctrine-project.org/projects/dbal.html",
            "keywords": [
                "abstraction",
                "database",
                "dbal",
                "mysql",
                "persistence",
                "pgsql",
                "php",
                "queryobject"
            ],
            "time": "2019-11-02T22:19:34+00:00"
        },
        {
            "name": "doctrine/event-manager",
            "version": "1.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/event-manager.git",
                "reference": "629572819973f13486371cb611386eb17851e85c"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/doctrine/event-manager/zipball/629572819973f13486371cb611386eb17851e85c",
                "reference": "629572819973f13486371cb611386eb17851e85c",
                "shasum": ""
            },
            "require": {
                "php": "^7.1"
            },
            "conflict": {
                "doctrine/common": "<2.9@dev"
            },
            "require-dev": {
                "doctrine/coding-standard": "^6.0",
                "phpunit/phpunit": "^7.0"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.0.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Doctrine\\Common\\": "lib/Doctrine/Common"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Guilherme Blanco",
                    "email": "guilhermeblanco@gmail.com"
                },
                {
                    "name": "Roman Borschel",
                    "email": "roman@code-factory.org"
                },
                {
                    "name": "Benjamin Eberlei",
                    "email": "kontakt@beberlei.de"
                },
                {
                    "name": "Jonathan Wage",
                    "email": "jonwage@gmail.com"
                },
                {
                    "name": "Johannes Schmitt",
                    "email": "schmittjoh@gmail.com"
                },
                {
                    "name": "Marco Pivetta",
                    "email": "ocramius@gmail.com"
                }
            ],
            "description": "The Doctrine Event Manager is a simple PHP event system that was built to be used with the various Doctrine projects.",
            "homepage": "https://www.doctrine-project.org/projects/event-manager.html",
            "keywords": [
                "event",
                "event dispatcher",
                "event manager",
                "event system",
                "events"
            ],
            "time": "2019-11-10T09:48:07+00:00"
        },
        {
            "name": "prestashop/prestashop-webservice-lib",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/PrestaShop/PrestaShop-webservice-lib.git",
                "reference": "d27733c262a00245b0636a2986d42b78957f8cf0"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/PrestaShop/PrestaShop-webservice-lib/zipball/d27733c262a00245b0636a2986d42b78957f8cf0",
                "reference": "d27733c262a00245b0636a2986d42b78957f8cf0",
                "shasum": ""
            },
            "require": {
                "ext-curl": "*",
                "ext-libxml": "*",
                "ext-simplexml": "*",
                "php": ">= 5.3.0"
            },
            "type": "library",
            "autoload": {
                "classmap": [
                    "PSWebServiceLibrary.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "OSL-3.0"
            ],
            "authors": [
                {
                    "name": "PrestaShop SA",
                    "email": "contact@prestashop.com"
                }
            ],
            "description": "PrestaShop Webservice access library",
            "time": "2020-05-06T10:18:26+00:00"
        },
        {
            "name": "psr/log",
            "version": "1.1.3",
            "source": {
                "type": "git",
                "url": "https://github.com/php-fig/log.git",
                "reference": "0f73288fd15629204f9d42b7055f72dacbe811fc"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/php-fig/log/zipball/0f73288fd15629204f9d42b7055f72dacbe811fc",
                "reference": "0f73288fd15629204f9d42b7055f72dacbe811fc",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.0"
            },
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.1.x-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Psr\\Log\\": "Psr/Log/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "PHP-FIG",
                    "homepage": "http://www.php-fig.org/"
                }
            ],
            "description": "Common interface for logging libraries",
            "homepage": "https://github.com/php-fig/log",
            "keywords": [
                "log",
                "psr",
                "psr-3"
            ],
            "time": "2020-03-23T09:12:05+00:00"
        },
        {
            "name": "sabre/event",
            "version": "2.0.2",
            "source": {
                "type": "git",
                "url": "https://github.com/sabre-io/event.git",
                "reference": "337b6f5e10ea6e0b21e22c7e5788dd3883ae73ff"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/sabre-io/event/zipball/337b6f5e10ea6e0b21e22c7e5788dd3883ae73ff",
                "reference": "337b6f5e10ea6e0b21e22c7e5788dd3883ae73ff",
                "shasum": ""
            },
            "require": {
                "php": ">=5.4.1"
            },
            "require-dev": {
                "phpunit/phpunit": "*",
                "sabre/cs": "~0.0.1"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Sabre\\Event\\": "lib/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "BSD-3-Clause"
            ],
            "authors": [
                {
                    "name": "Evert Pot",
                    "email": "me@evertpot.com",
                    "homepage": "http://evertpot.com/",
                    "role": "Developer"
                }
            ],
            "description": "sabre/event is a library for lightweight event-based programming",
            "homepage": "http://sabre.io/event/",
            "keywords": [
                "EventEmitter",
                "events",
                "hooks",
                "plugin",
                "promise",
                "signal"
            ],
            "time": "2015-05-19T10:24:22+00:00"
        },
        {
            "name": "vlucas/spot2",
            "version": "v2.2.1",
            "source": {
                "type": "git",
                "url": "https://github.com/spotorm/spot2.git",
                "reference": "e4ada9591a2900fbb8dd9c81862772f9b3d998a3"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/spotorm/spot2/zipball/e4ada9591a2900fbb8dd9c81862772f9b3d998a3",
                "reference": "e4ada9591a2900fbb8dd9c81862772f9b3d998a3",
                "shasum": ""
            },
            "require": {
                "doctrine/dbal": "^2.5.4",
                "php": ">=5.4.0",
                "sabre/event": "~2.0",
                "vlucas/valitron": "~1.1"
            },
            "require-dev": {
                "phpunit/phpunit": "^4.8"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Spot\\": "lib/",
                    "SpotTest\\": "tests/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "BSD"
            ],
            "authors": [
                {
                    "name": "Vance Lucas",
                    "email": "vance@vancelucas.com",
                    "homepage": "http://www.vancelucas.com"
                }
            ],
            "description": "Simple DataMapper built on top of Doctrine DBAL",
            "homepage": "https://github.com/vlucas/spot2",
            "keywords": [
                "database",
                "datamapper",
                "dbal",
                "doctrine",
                "entity",
                "mapper",
                "model",
                "orm"
            ],
            "time": "2018-10-09T10:05:13+00:00"
        },
        {
            "name": "vlucas/valitron",
            "version": "v1.4.7",
            "source": {
                "type": "git",
                "url": "https://github.com/vlucas/valitron.git",
                "reference": "a03072bed1679660200766d134507a30193eaf6d"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/vlucas/valitron/zipball/a03072bed1679660200766d134507a30193eaf6d",
                "reference": "a03072bed1679660200766d134507a30193eaf6d",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.2"
            },
            "require-dev": {
                "phpunit/phpunit": "^4.8.35 || ^5.5 || ^6.5"
            },
            "suggest": {
                "ext-mbstring": "It can support the multiple bytes string length."
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Valitron\\": "src/Valitron"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "BSD-3-Clause"
            ],
            "authors": [
                {
                    "name": "Vance Lucas",
                    "email": "vance@vancelucas.com",
                    "homepage": "http://www.vancelucas.com"
                }
            ],
            "description": "Simple, elegant, stand-alone validation library with NO dependencies",
            "homepage": "http://github.com/vlucas/valitron",
            "keywords": [
                "valid",
                "validation",
                "validator"
            ],
            "time": "2019-08-29T19:49:43+00:00"
        }
    ],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": {
        "prestashop/prestashop-webservice-lib": 20
    },
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": [],
    "platform-dev": []
}
```

**Comment by humanitiesclinic** [comment]
I tried to update but nothing is happening:

```
$ php --version
PHP 7.2.10 (cli) (built: Oct  9 2018 14:56:43) ( NTS )
Copyright (c) 1997-2018 The PHP Group

$ composer update atk4/ui
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by humanitiesclinic** [comment]
I am not sure if the version is the problem in the first place though... I tried changing all that was suggested by @DarkSide666 like so:

```
<?php
require 'vendor/autoload.php';
use atk4\ui\Form; // just declared once at the top of your file

// Initialize App and Layout first
$app = new \atk4\ui\App('My First App');
$app->initLayout(\atk4\ui\Layout\Centered::class);

// Your application starts here
$app->layout->add('HelloWorld');

$form = Form::addTo($app);
$form->addField('email');

?>
```

But still having error..

**Comment by humanitiesclinic** [comment]
In fact, I have this now as the error:

```
Error: Class '\atk4\ui\Layout\atk4\ui\Layout\Centered' not found (in /Users/user/Documents/canla_prods/vendor/atk4/core/src/FactoryTrait.php:153)
#0 /Users/user/Documents/canla_prods/vendor/atk4/ui/src/App.php(324): atk4\ui\App->factory(Array, Array, 'Layout')
#1 /Users/user/Documents/canla_prods/agileui_test.php(7): atk4\ui\App->initLayout('atk4\\ui\\Layout\\...')
#2 {main}
```

**Comment by humanitiesclinic** [comment]
Any one here can help? I literally just downloaded the library via Composer without any customisation, and followed all instructions. And I am getting this... Is it because my PHP version is 7.1.16? I tried to change it to 7.2 onwards by using another PHP binary in another folder and including its path in the PATH of my shell, and then tried to update agileui, but to no avail - it says that there's nothing to update.

**Comment by DarkSide666** [comment]
You should definitely use latest version 2.1.x if you can.
So in composer.json use:
```
        "atk4/ui": "^2.1.0"
```

**Comment by mvorisek** [comment]
You must use a newer version as advised
